#include <iostream>
#include <vector>
#include <cstring>      // for strerror()
#include <cassert>

#include <sys/socket.h> // for socket creation
#include <netinet/ip.h> // for internal protocol addresses
#include <unistd.h>     // for read(), write(), close()
#include <fcntl.h>      // for F_SETFL, O_NONBLOCK
#include <poll.h>

#include "common.h"

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming;  // data to be parsed by the application
    std::vector<uint8_t> outgoing;  // responses generated by the application
};

static void fd_set_nonblock(int fd) {
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
}

static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}

static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

static void print_as_chars(const uint8_t *bytes, int32_t len) {
    for (int32_t i=0;i<len;i++) {
        std::cout << static_cast<char>(bytes[i]);
    }

    std::cout << "\n";
}

// Read header + body. Write response.
static int32_t try_one_request(Conn *conn) {
    // == Read header ==
    if (conn->incoming.size() < 4) {
        return false;
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if(len > SOMAXCONN) { // Error: request too long
        conn->want_close = true;
        return false;
    }

    // == Read body ==
    if(4 + len > conn->incoming.size()) { // Error: expected body too short
        return false;
    }

    const uint8_t *request = &conn->incoming[4];
    print_as_chars(request, len);

    
    // == Generate response (echo) ==
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);
    
    buf_consume(conn->incoming, 4 + len); // Remove read data from Conn::incoming ?????????
    return true; // success
}

static Conn *handle_accept(int fd) {
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);

    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if(connfd < 0) {
        return NULL; // error
    }
    fd_set_nonblock(connfd);

    // Create Connection obj for the raw fd. Fd is just an int
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    return conn;

}

static void handle_read(Conn *conn) {
    // 1. Non-blocking read
    uint8_t buf[64*1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if(rv <=0 ) {  // handle error or EOF
        conn->want_close = true;
        return;
    }

    // 2. Add new data to the Conn::incoming buffer
    buf_append(conn->incoming, buf, (size_t)rv);

    try_one_request(conn);

    if(conn->outgoing.size() > 0) {
        conn->want_read = false;
        conn->want_write = true;
    } // else: want read
}

static void handle_write(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(rv < 0) {
        conn->want_close = true; 
        return;
    }

    buf_consume(conn->outgoing, (size_t) rv);

    if(conn->outgoing.size() == 0) {
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

int main() {
    std::cout << "Running Server: " << "\n";

    // ==== Create listening socket ====

    int fd = socket(AF_INET, SOCK_STREAM, 0);                       // 1. Obtain a socket handle. We choose IPV4, TCP

    int val = 1;                                                    // Set socket option SO_REUSEADDR to allow server
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));    // to use same IP:port immediately after restart. 
    fd_set_nonblock(fd);                                            // Make listening socket non-blocking. 

    struct sockaddr_in addr = {};                                   // 2. Bind to an address. We use wildcard 0.0.0.0:1234
    addr.sin_family = AF_INET;          // address family IPv4
    addr.sin_port = htons(1234);        // port 1234
    addr.sin_addr.s_addr = htonl(0);    // wildcard- accept connections anywhere
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) {die("bind()");} // rv: 0 = success, -1 = error

    rv = listen(fd, SOMAXCONN);                                     // 3. Listen. Socket is created on listen(). SOMAXCONN is the 
    if (rv) die("listen()");                                        //    maximum queue size for pending connections. It's 4096 on linux.
                                                                    //    For modern use-case it has no affect, the queue never fills up.  

    // ==== Event loop ====
    std::vector<Conn *> fd2Conn; // map of client connections, keyed by fd
    std::vector<struct pollfd> poll_args;
    while(true) {
        // 1. Prepare the arguments of poll()
        poll_args.clear();
        // place the listening socket in first position
        struct pollfd pfd = {fd, POLLIN, 0}; // args: fd, event, revents
        poll_args.push_back(pfd);

        // place connection sockets after
        for (Conn *conn : fd2Conn) {
            if(!conn) {
                continue;
            }
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            if(conn->want_read) {
                pfd.events |= POLLIN;
            }
            if(conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // 2. Wait for readiness with poll()
        int rv = poll(poll_args.data(), (nfds_t) poll_args.size(), -1);
        if (rv < 0 && errno == EINTR) {
            continue; // EINTR means syscall was interrupted. not an error
        }
        if(rv < 0) {
            die("poll() error");
        }

        // 3. Handle new connections with the listening socket
        if(poll_args[0].revents) { 
            if(Conn *conn = handle_accept(fd)) {
                // put into map
                if(fd2Conn.size() <= (size_t) conn->fd) {
                    fd2Conn.resize(conn->fd+1);
                }
                fd2Conn[conn->fd] = conn;
            }
        }

        // 4. Invoke callbacks for connection sockets. 
        for(size_t i = 1;i<poll_args.size();i++) {
            // Get status and connection
            uint32_t ready = poll_args[i].revents;
            Conn *conn = fd2Conn[poll_args[i].fd];
            // Read & write
            if(ready & POLLIN) {
                handle_read(conn);
            }
            if(ready & POLLOUT) {
                handle_write(conn);
            }
            // Close connection if needed (potentially from error) 
            if((ready & POLLERR) || conn->want_close) {
                (void) close(conn->fd);
                fd2Conn[conn->fd] = NULL;
                delete conn; // needed since we create `Conn` object with `new`
            }
        }

    }
    
    return 0;
}